# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdwalker < Formula
  desc "AI agent 输出物专用终端 Markdown 工作台"
  homepage "https://github.com/Bairea/mdwalker"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Bairea/mdwalker/releases/download/v0.1.1/mdwalker_0.1.1_darwin_amd64.tar.gz"
      sha256 "432bbf355482893c1975ac04d71a9ae456eb71bedbd82d52173f90ffe9d13e37"

      define_method(:install) do
        bin.install "mdwalker"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Bairea/mdwalker/releases/download/v0.1.1/mdwalker_0.1.1_darwin_arm64.tar.gz"
      sha256 "10ff884d5ae9700ff1f8b92c155f4e16a8ca3120319cd60d907aac5f37095138"

      define_method(:install) do
        bin.install "mdwalker"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bairea/mdwalker/releases/download/v0.1.1/mdwalker_0.1.1_linux_amd64.tar.gz"
      sha256 "970b27558e8fcf5a39a25ab9f9f6dcd4b1fcee3c8aef12c2100c598569d3e0bc"
      define_method(:install) do
        bin.install "mdwalker"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Bairea/mdwalker/releases/download/v0.1.1/mdwalker_0.1.1_linux_arm64.tar.gz"
      sha256 "5f3dcb9e12fb957b4fd254069f13a9f412d9f9ce3072242e794c23b6c10fbe47"
      define_method(:install) do
        bin.install "mdwalker"
      end
    end
  end
end
